name: Calculator Tests by @balaji303

# Trigger Pipeline on these conditions
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    #Environment is based on Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      #Set up python on the environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          
      # Run pytest on test_calculator.py and generate report
      - name: Run tests and generate HTML report
        run: |
          pytest --html=report.html app/test_calculator.py

      # Upload the test report as artifact
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            report.html
            assets/

      # Run test for CodeCov
      - name: Run tests
        run: |
          pytest --cov --cov-report=xml

      # Upload result to Codecov using Tokens
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
