name: Python Tests by @balaji303

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          
      # - name: Run tests and generate coverage report2
      #   run: |
      #     pytest pytest app/test_calculator.py --cov=calculator --cov-report=html

      # - name: Upload coverage report2
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: coverage-report2
      #     path: htmlcov/

      - name: Run tests and generate HTML report
        run: |
          pytest --html=report.html app/test_calculator.py

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            report.html
            assets/

      - name: Run tests
        run: |
          pytest --cov --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # - name: Upload assets folder
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: assets
      #     path: assets/

          
      # - name: Run tests and generate coverage report1
      #   run: |
      #     pytest app/test_calculator.py --cov=app.calculator --cov-report=html

      # - name: Upload coverage report1
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: coverage-report1
      #     path: htmlcov/
